version: '3.9'
services:
#  nest-api:
#    container_name: nest-api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - .env
#    ports:
#      - 9229:9229
#    depends_on:
#      - postgres

  postgres:
    image: postgres
    container_name: postgres_modern
    restart: always
    ports:
      - 4948:4948
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: modern_db

