version: '3.9'
services:      
  postgres-dev:
    image: postgres
    container_name: postgres-dev
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.dev
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db-dev

